language: perl
sudo: false
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1 DDPTESTCOVERAGE=1
  allow_failures:
    - perl: blead
before_install:
 - eval $(curl https://travis-perl.github.io/init) --auto
notifications:
  email: false
