language: perl
sudo: false
matrix:
  include:
    - perl: 5.28
      env: COVERAGE=1 DDPTESTCOVERAGE=1
  allow_failures:
    - perl: blead
before_install:
 - cpanm --installdeps --notest .
 - perl Makefile.PL
 - make
 - make test
 
notifications:
  email: false
